language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
    - npm link
jobs:
  include:
    - stage: build
      script:
        - echo CREATE PR
        - npm i
        - create-branch $GIT_USER $GIT_TOKEN $REPO
        - npm run release
        - follow-tags $GIT_USER $GIT_TOKEN $REPO
        - create-PR $GIT_USER $GIT_TOKEN $REPO
    - stage: release
      script:
        - echo DEPLOY version
stages:
  - name: build
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: release
    if: (branch = release/*)
