language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
    - npm link
jobs:
  include:
    - stage: build
      script:
        - echo CREATE PR
        - npm i
        - create-branch $GIT_USER $REPO $GIT_TOKEN
        - npm run release
        - create-PR $GIT_USER $REPO $GIT_TOKEN
stages:
  - name: build
    if: (branch = master)