language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
    - npm link
jobs:
  include:
    - stage: build
      name: "CREATE PR"
      script:
        - npm i
        - create-branch $GIT_USER $GIT_TOKEN $REPO
        - npm run release
        - follow-tags $GIT_USER $GIT_TOKEN $REPO
        - create-PR $GIT_USER $GIT_TOKEN $REPO
    - stage: release
      name: "DEPLOY RELEASE"
      script:
        - echo desplegar
stages:
  - name: build
    if: type != pull_request AND branch = master
  - name: release
    if: branch =~ /release\/.*/
