language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
jobs:
  include:
    - stage: test
      script:
        - echo otra rama
    - stage: build
      script:
        - echo hola
stages:
  - name: build
    if: (branch = build_ci_third_attempt)
  - name: test
    if: (branch = build_ci_third_attempt)