language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
jobs:
    include:
        - stage: script
          if: branch = master
              - npm i
              - create-branch
              - npm run release
              - follow-tags
              - create-PR