language: node_js
node_js:
    - node
    - 12
before_install:
    - npm i -g simple-git
    - chmod -R +x bin/*.js
script:
    if: branch = master
        - echo MASTER
    if: branch = build_ci_third_attempt
        - echo otra rama